baseURL = 'https://kirisamemagicshop.github.io/'
languageCode = 'zh-cn'
title = 'Kirisame Magic Shop'
theme = 'PaperMod'
copyright = '© Article authors'

[outputs]
home = ['html', 'rss', 'json']

[[menu.main]]
name = 'Search'
url = 'search/'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [['$$', '$$']], inline = [['$', '$']] }

[params.homeInfoParams]
Title = "雾雨魔法店"
Content = """\
PLT，以及魔法。

目前主要作为同名知乎专栏的公开镜像。
"""

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/KirisameMagicShop/kirisamemagicshop.github.io"

[[params.socialIcons]]
name = "Zhihu"
url = "https://www.zhihu.com/column/marisa"
