baseURL = 'https://kirisamemagicshop.github.io/'
languageCode = 'zh-cn'
title = 'Kirisame Magic Shop'
theme = 'PaperMod'
copyright = """\
[Kirisame Magic Shop](https://kirisamemagicshop.github.io) © 2024 is licensed
under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)
"""

[outputs]
home = ['html', 'rss', 'json']

[[menu.main]]
name = 'Search'
url = 'search/'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [['$$', '$$']], inline = [['$', '$']] }

[params.homeInfoParams]
Title = "雾雨魔法店"
Content = """\
PLT，以及魔法。

目前主要作为同名知乎专栏的公开镜像。
"""
