baseURL = 'https://kirisamemagicshop.github.io/'
languageCode = 'zh-cn'
title = 'Kirisame Magic Shop'
theme = 'PaperMod'
copyright = '© Article authors'

[outputs]
home = ['html', 'rss', 'json']

[[menu.main]]
name = 'Search'
url = 'search/'

[[menu.main]]
name = 'Tags'
url = 'tags/'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [['$$', '$$']], inline = [['$', '$']] }

[params.homeInfoParams]
Title = "雾雨魔法店"
Content = """\
FP，PLT，以及适量的蘑菇。

目前主要作为同名知乎专栏的公开镜像，也收录同类型专栏中的作品以及作者独立提交的文章。

> 致各位知乎文章作者：若您的作品被雾雨魔法店收录，并且同意本站转载您的文章，
> [请点击这里](https://github.com/KirisameMagicShop/kirisamemagicshop.github.io/issues/1)
> 在评论中留下您的知乎 ID 或主页链接。非常感谢您的贡献。
"""

[params]
defaultTheme = "auto"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/KirisameMagicShop/kirisamemagicshop.github.io"

[[params.socialIcons]]
name = "Zhihu"
url = "https://www.zhihu.com/column/marisa"

[[params.socialIcons]]
name = "RSS"
url = "https://kirisamemagicshop.github.io/index.xml"
